#!/bin/bash

if [ ! -f ~/.jwmrc ]; then
	# Configuration file not found
	if [ ! -d ~/.config/jwm/ ]; then
		mkdir -p ~/.config/jwm
	fi
	# Copy configuration file
        if [ -d /usr/share/jwm/ ]; then
		# Copy all files from there
		cp /usr/share/jwm/* ~/.config/jwm
	elif [ -f /etc/system.jwmrc ]; then
		# Arch linux
		cp /etc/system.jwmrc ~/.config/jwm/jwmrc
	elif [ -f /etc/jwm/jwmrc ]; then
		# Ubuntu linux
		cp /etc/jwm/jwmrc ~/.config/jwm/jwmrc	
	fi
	# Check if exist configuration file
	if [ -f ~/.config/jwm/jwmrc ] ; then
		# Make symbolic link to home
		ln -s ~/.config/jwm/jwmrc ~/.jwmrc
	fi
fi

exec jwm 
